backend:
  name: git-gateway
  branch: main

media_folder: '~/assets/images'
public_folder: '/_astro'

collections:
  - name: 'post'
    label: 'Post'
    folder: 'src/data/post'
    create: true
    identifier_field: 'id'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string' } # fix max length
      - { label: 'Highlight', name: 'highlight', widget: 'boolean', default: false }
      # - {
      #     label: "ID",
      #     name: "id",
      #     widget: "number",
      #     default: "{{add entries.length 1}}", 
      #     required: true
      #   }
        # fix for auto increment id
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Publish Date', name: 'publishDate', widget: 'datetime', required: false }
      # - { label: 'Image', name: 'image', widget: 'string' , default: '~/assets/images/' } 
      - { label: 'Image', name: 'image', widget: 'image' } 

      - { label: 'Category', name: 'category', widget: 'string' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          allow_add: true,
          allow_delete: true,
          collapsed: false,
          field: { label: 'Tag', name: 'tag', widget: 'string' },
        }
      - { label: 'Content', name: 'body', widget: 'markdown' }
      - {
          label: 'Metadata',
          name: 'canonical',
          widget: 'hidden',
          default: '{{site.url}}/blog/{{slug}}',
        }
