backend:
  name: git-gateway
  branch: main

media_folder: 'src/assets/images'
public_folder: '/assets/images'

site_url: 'https://tobost-certified.netlify.app/'
logo_url: 'src/assets/favicons/favicon.webp'

stylesheet: '/admin/preview-styles.css'

collections:
  - name: 'post'
    label: 'Post'
    folder: 'src/data/post'
    create: true
    identifier_field: 'id'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string' } 
      - { label: 'Highlight', name: 'highlight', widget: 'boolean', default: false }
      - { label: 'Publish Date', name: 'publishDate', widget: 'datetime' }
      - { label: 'Image', name: 'image', widget: 'image' }

      - { label: 'Content', name: 'body', widget: 'markdown' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          allow_add: true,
          allow_delete: true,
          collapsed: false,
          required: false,
          field: { label: 'Tag', name: 'tag', widget: 'string' },
        }

      - { label: 'Author', name: 'author', widget: 'string', default: 'Tobost06' }
      - { label: 'Metadata', name: 'canonical', widget: 'hidden', default: '{{site.url}}/blog/{{slug}}' }
      # - {
      #     label: "ID",
      #     name: "id",
      #     widget: "number",
      #     default: "{{add entries.length 1}}",
      #     required: true
      #   }
      # fix for auto increment id
